CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code VARCHAR(255) NOT NULL,
    subject_name VARCHAR(255) NOT NULL,
    weight INTEGER NOT NULL,
    slot_duration INTEGER NOT NULL,
    subject_type INTEGER NOT NULL,
    CONSTRAINT uq_subjects_subject_code UNIQUE (subject_code)
);

CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    CONSTRAINT uq_teachers_email UNIQUE (email)
);

CREATE TABLE teacher_subjects (
    teacher_id BIGINT NOT NULL REFERENCES teachers (id),
    subject_id BIGINT NOT NULL REFERENCES subjects (id),
    PRIMARY KEY (teacher_id, subject_id)
);

CREATE TABLE batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    section VARCHAR(255) NOT NULL,
    strength INTEGER NOT NULL
);

CREATE TABLE batch_subjects (
    batch_id BIGINT NOT NULL REFERENCES batches (id),
    subject_id BIGINT NOT NULL REFERENCES subjects (id),
    PRIMARY KEY (batch_id, subject_id)
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL,
    fixed_batch_id BIGINT REFERENCES batches (id),
    CONSTRAINT uq_rooms_name UNIQUE (name)
);

CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL REFERENCES subjects (id),
    teacher_id BIGINT NOT NULL REFERENCES teachers (id),
    batch_id BIGINT NOT NULL REFERENCES batches (id),
    preferred_room_id BIGINT REFERENCES rooms (id)
);

CREATE TABLE scheduled_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES sessions (id),
    day_of_week INTEGER NOT NULL,
    start_slot INTEGER NOT NULL,
    room_id BIGINT NOT NULL REFERENCES rooms (id)
);
