CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR(255) NOT NULL,
    entity_id BIGINT,
    action VARCHAR(20) NOT NULL,
    snapshot TEXT,
    performed_by VARCHAR(255) NOT NULL,
    performed_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_log_entity ON audit_log (entity_name, entity_id);
