 # PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/kronos_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Server
server.port=8080
# Logging
logging.level.root=INFO
logging.level.com.kronostt=INFO